#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


# MY STUFF

# change keyboard layout
setxkbmap pt

# Disable tapping and scrolling in touchpad while typing
syndaemon -i 0.5 -t -K -R -d

# Fix issue where android-studio opens as blank window
export _JAVA_AWT_WM_NONREPARENTING=1

# Starting WM/DE chosen
session=${1:-bspwm}

case $session in
    bspwm ) exec bspwm        ;;
    mate  ) exec mate-session ;;
    *) echo "Unknown session" ;;
esac
