#!/bin/sh

settings(){
  setting_options="Change wallpaper\nChange theme\nChoose default pdf viewer\nChoose monitor order (multiple monitors)\nPair wallpaper to theme\nSet keyboard layout\nSound\nToggle touchpad"
  choice=$(echo $setting_options | rofi -dmenu -i -p "Choose setting")
  case $choice in
    "Change wallpaper")
      wpchoose
      ;;
    "Change theme")
      theme_selector
      ;;
    "Choose default pdf viewer")
      default_pdf
      ;;
    "Choose monitor order (multiple monitors)")
      bspwm_monitor_order
      ;;
    "Pair wallpaper to theme")
      wptheme
      ;;
    "Set keyboard layout")
      setkblayout
      ;;
    "Sound")
      pavucontrol
      ;;
    "Toggle touchpad")
      touchpad_toggle
      ;;
  esac
}

games(){
  game_options="Steam\n"
  choice=$(echo $game_options | rofi -dmenu -i -p "Choose game/client")
  case $choice in
    "Steam")
      steam
      ;;
  esac
}

tools(){
  tool_options="Calculator\nGimp\nDiscord"
  choice=$(echo $tool_options | rofi -dmenu -i -p "Choose tool")
  case $choice in
    "Calculator")
      calculator
      ;;
    "Gimp")
      gimp
      ;;
    "Discord")
      discord
      ;;
  esac
}

entertainment(){
  entertainment_options="Spotify\nNetflix"
  choice=$(echo $entertainment_options | rofi -dmenu -i -p "Choose option")
  case $choice in
    "Spotify")
      spotify
      ;;
    "Netflix")
      netflix_web
      ;;
  esac
}

prompt(){
  choice=$(echo "Yes\nNo" | rofi -dmenu -i -p "Are you sure you want to "$1"?")
  if [ -z "$choice" ] || [ "$choice" = "No" ] ; then
    exit
  fi 
}

menu_items="Settings\nTools\nGames\nInternet\nEntertainment\nTerminal\nLogout\nShutdown\nReboot"

menu_choice=$(echo $menu_items | rofi -dmenu -i -p "Choose option")

case $menu_choice in
  "Settings")
    settings
    ;;
  "Tools")
    tools
    ;;
  "Games")
    games
    ;;
  "Internet")
    $BROWSER
    ;;
  "Entertainment")
    entertainment
    ;;
  "Terminal")
    $TERMINAL
    ;;
  "Logout")
    prompt "logout"
    bspwmctl quit
    ;;
  "Shutdown")
    prompt "shutdown"
    shutdown now
    ;;
  "Reboot")
    prompt "reboot"
    reboot
    ;;
esac

