#!/bin/sh

#Change accent color in rofi theme
sub_ac(){
  cp $XDG_CONFIG_HOME/rofi/theme.rasi $CACHE/theme.rasi
  sed -i "s/color4: #[0-9a-zA-Z]*/color4: $1/" $CACHE/theme.rasi
}

#Change selected foreground color in rofi theme
sub_selfg(){
  sed -i "s/color6: #[0-9a-zA-Z]*/color6: $1/" $CACHE/theme.rasi
}

restart=1
choice=""

while [ ! -z "$1" ] ; do
  case $1 in
    -t | --theme) #Pick a theme without rofi
      shift
      choice=$1
      ;;
    -nr) #Do not restart bspwm in the end
      restart=0
      ;;
  esac
  shift
done

if [ -z "$choice" ] ; then
  themes="Blue\nGreen\nOrange\nPink\nPurple\nRed\nTurquoise\nWhite\nYellow"
  choice=$(echo $themes | rofi -dmenu -i -p "Choose a theme")
fi
[ -z $choice ] && exit

case $choice in 
  "Blue")
    sub_ac "#3065ba"
    sub_selfg "#000000"
    echo "bspwm_color=#3065ba" > $CACHE/theme.txt
    echo "polybar_bgcolor=#3065ba" >> $CACHE/theme.txt
    echo "polybar_fgcolor=#ffffff" >> $CACHE/theme.txt
    ;;
  "Green")
    sub_ac "#0cc731"
    sub_selfg "#000000"
    echo "bspwm_color=#0cc731" > $CACHE/theme.txt
    echo "polybar_bgcolor=#9002a802" >> $CACHE/theme.txt
    echo "polybar_fgcolor=#ffffff" >> $CACHE/theme.txt
    ;;
  "Orange")
    sub_ac "#ff910a"
    sub_selfg "#000000"
    echo "bspwm_color=#ff910a" > $CACHE/theme.txt
    echo "polybar_bgcolor=#ff910a" >> $CACHE/theme.txt
    echo "polybar_fgcolor=#000000" >> $CACHE/theme.txt
    ;;
  "Pink")
    sub_ac "#ff5eb9"
    sub_selfg "#000000"
    echo "bspwm_color=#ff5eb9" > $CACHE/theme.txt
    echo "polybar_bgcolor=#ff5eb9" >> $CACHE/theme.txt
    echo "polybar_fgcolor=#000000" >> $CACHE/theme.txt
    ;;
  "Purple")
    sub_ac "#ca10eb"
    sub_selfg "#000000"
    echo "bspwm_color=#ca10eb" > $CACHE/theme.txt
    echo "polybar_bgcolor=#90ca10eb" >> $CACHE/theme.txt
    echo "polybar_fgcolor=#ffffff" >> $CACHE/theme.txt
    ;;
  "Red")
    sub_ac "#fa2828"
    sub_selfg "#000000"
    echo "bspwm_color=#fa2828" > $CACHE/theme.txt
    echo "polybar_bgcolor=#90ff0000" >> $CACHE/theme.txt
    echo "polybar_fgcolor=#ffffff" >> $CACHE/theme.txt
    ;;
  "Turquoise")
    sub_ac "#40E0D0"
    sub_selfg "#000000"
    echo "bspwm_color=#40E0D0" > $CACHE/theme.txt
    echo "polybar_bgcolor=#40E0D0" >> $CACHE/theme.txt
    echo "polybar_fgcolor=#000000" >> $CACHE/theme.txt
    ;;
  "White")
    sub_ac "#ffffff"
    sub_selfg "#000000"
    echo "bspwm_color=#ffffff" > $CACHE/theme.txt
    echo "polybar_bgcolor=#ffffff" >> $CACHE/theme.txt
    echo "polybar_fgcolor=#000000" >> $CACHE/theme.txt
    ;;
  "Yellow")
    sub_ac "#ffe53d"
    sub_selfg "#000000"
    echo "bspwm_color=#ffe53d" > $CACHE/theme.txt
    echo "polybar_bgcolor=#ffe53d" >> $CACHE/theme.txt
    echo "polybar_fgcolor=#000000" >> $CACHE/theme.txt
    ;;
esac

[ $restart = 1 ] && bspwmctl restart
