#!/bin/sh

device=$(xinput | grep -i touchpad | grep -o "id=[0-9]*" | cut -d "=" -f 2)
if [ -z "$(xinput list-props $device | grep -e "Device Enabled.*:.*1")" ]; then
  xinput enable $device 
  notify-send "Touchpad Status" "Enabled"
else
  xinput disable $device
  notify-send "Touchpad Status" "Disabled"
fi
