#!/bin/sh

wall_name=$(find "$HOME/Pictures/wallpapers" -type f | awk -F"/" '{print $NF}' | rofi -dmenu -p "Choose a wallpaper")
[ -z "$wall_name" ] && exit

wall_path=$(find "$HOME/Pictures/wallpapers" -name "$wall_name")
[ ! "$(echo $wall | sed 's/ /\n/g' | wc -l)" = "1" ] && notify-send "Wallpaper" "Two or more wallpapers have the same name" && exit

themes="Blue\nGreen\nOrange\nPink\nPurple\nRed\nTurquoise\nWhite\nYellow\nNone"
theme=$(echo $themes | rofi -dmenu -i -p "Choose a theme")
[ -z $theme ] && exit

file=$CACHE/wptheme.txt
[ $theme = "None" ] && sed -i "/$wall_name/d" $file && exit

if [ ! -e "$file" ] ; then 
  echo "$wall_name $theme" > $file
elif [ -z "$(grep -w $wall_name $file)" ] ; then
  echo "$wall_name $theme" >> $file
else
  sed -i "s/$wall_name.*/$wall_name $theme/" $file
fi

wpchoose $wall_name

