#! /bin/sh

# Start picom for transparency
picom --config $XDG_CONFIG_HOME/picom/picom.conf -b

# Lauch sxhkd
sxhkd &

# Start notification server
dunst &

# Start power manager
xfce4-power-manager &

# Checks if monitor list exists
if [ -z "$(find $CACHE/monitor_order.txt 2>/dev/null)" ] ; then
  mode="default" bspwm_monitor_order
fi

# Checks if theme as been previously defined 
if [ -z "$(find $CACHE/theme.txt 2>/dev/null)" ] ; then
  theme_selector default
fi

# Initializes desktops in all connected monitors
bspwm_monitor_conf

# Launch polybar
$HOME/.config/polybar/launch.sh

# Start network manager applet
nm-applet &

# Start udiskie for automatically mounting drives (no notifications for now)
udiskie --tray &

# Daemon that removes empty desktops and reorders they names appropriately 
bspwm_rm_empty_desktops &

bspc config border_width        3
bspc config window_gap          10
#bspc config focused_border_color "#ffff00" #YELLOW
#bspc config focused_border_color "#ffffff" #WHITE
#bspc config focused_border_color "#ff0000" #RED
bspc config focused_border_color "#14ed00" #GREEN
#bspc config focused_border_color "#f5982f" #ORANGE
#bspc config focused_border_color "#f5982f" #ORANGE
#bspc config focused_border_color "#3065ba" #BLUE

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_monitor true

# Rules 
#bspc rule -a Gimp state=floating 
bspc rule -a steam state=tiled follow=no
#bspc rule -a 'Android Emulator - Nexus_5X_API_29_x86:5554' state=floating
# bspc rule -a $BROWSER desktop='^2' follow=on
#bspc rule -a Screenkey manage=off
