#! /bin/sh

# Start picom for transparency
picom -b

# Random wallpaper
wpshuffle

# Lauch sxhkd
sxhkd &

# Start network manager applet
nm-applet &

# Start udiskie for automatically mounting drives (no notifications for now)
udiskie --tray &

# Start notification server
dunst &

# Start power manager
xfce4-power-manager &

# Lauch polybar
$HOME/.config/polybar/launch.sh

# Initializes desktops in all conected monitors
bspwm_monitor_conf

# Daemon that removes empty desktops and reorders they names apropriatly 
bspwm_rm_empty_desktops &

bspc config border_width        3
bspc config window_gap          10
#bspc config focused_border_color "#ffff00" #YELLOW
#bspc config focused_border_color "#ffffff" #WHITE
#bspc config focused_border_color "#ff0000" #RED
bspc config focused_border_color "#14ed00" #GREEN
#bspc config focused_border_color "#f5982f #ORANGE

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_monitor true

# Rules 
bspc rule -a Gimp state=floating 
# bspc rule -a $BROWSER desktop='^2' follow=on
#bspc rule -a Screenkey manage=off
