#! /bin/sh

# Start picom for transparency
picom -b

# Start feh for wallpaper
feh --randomize --bg-scale $HOME/Pictures/wallpapers/* &

# Lauch sxhkd
sxhkd &

# Lauch polybar
$HOME/.config/polybar/launch.sh

# Start network manager applet
nm-applet &

# Start bluetooth tray applet
blueman-applet &

# Start udiskie for automatically mounting drives (no notifications for now)
udiskie --tray &

# Start notification server
dunst &

# Start power manager
xfce4-power-manager &



bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        3
bspc config window_gap          10
#bspc config focused_border_color "#ffff00" #YELLOW
#bspc config focused_border_color "#ffffff" #WHITE
#bspc config focused_border_color "#ff0000" #RED
bspc config focused_border_color "#14ed00" #GREEN
#bspc config focused_border_color "#f5982f #ORANGE

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rule examples (not being used)
bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a $BROWSER desktop='^2' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
