#!/bin/sh

make_desktops(){
  #Makes 1 desktop in monitor $1, unless there already desktops on that monitor
  desktop_count=$(bspc query -m "$1" -D --names | wc -l)
  if [ $desktop_count -eq 1 ];then
    notify-send "Monitor '$1'" "Making desktop"
    bspc monitor "$1" -d "$1""-""1"
  fi
}

#monitor_order.txt contains all monitors sorted from left to right
monitors=$(cat $CACHE/monitor_order.txt)
last=""

for monitor in $monitors ; do
  cn_monitor=$(xrandr | grep -w connected | grep -w "$monitor" | awk {'print $1'})
  if [ ! -z $cn_monitor ] ; then
    if [ -z $last ] ; then
      #Left monitor
      last="$monitor"
      xrandr --output "$monitor" --primary --auto
      make_desktops $monitor
    else
      xrandr --output "$monitor" --right-of "$last" --auto 
      last="$monitor"
      make_desktops $monitor
    fi
  fi
done

dc_monitors=$(xrandr | grep -w disconnected | awk {'print $1'})
for monitor in $dc_monitors ; do
  xrandr --output "$monitor" --off 
done
