#!/bin/sh

stylus_id=$(xsetwacom --list devices | grep -i stylus | tr -d -c 0-9)

[ -z "$stylus_id" ] && exit

monitors=$(xrandr | grep connected | cut -d " " -f 1)
monitor=$(echo "$monitors" | rofi -dmenu -i -p "Choose which monitor to map the wacom tablet to")
[ -z "$monitor" ] && exit

output=$(xsetwacom --set "$stylus_id" MapToOutput $monitor 2>&1)
echo $output
[ -z "$(echo $output | grep "Unable")" ] && exit

number=$(grep -n $monitor $CACHE/monitor_order.txt | cut -d ":" -f 1)
number=$(expr $number - 1)
xsetwacom --set "$stylus_id" MapToOutput HEAD-$number
