#!/bin/sh

dir=$(dirname "$1")
base=${1%.*}

case "$1" in
  *.tex)
    if [ -f "$dir/main.tex" ]; then
      $(cat $CACHE/default_pdf.txt) "$dir/main.pdf" &
    else
      $(cat $CACHE/default_pdf.txt) "$base.pdf" &
    fi
    ;;
  *.bib)
    if [ -f "$dir/main.tex" ]; then
      $(cat $CACHE/default_pdf.txt) "$dir/main.pdf" &
      echo
    fi
    ;;
  *.py)
    if [ -z "$(grep 'from manim import' $1)" ]; then
      python $1
    else
      manim --write_to_movie $1
    fi
    ;;
  *.pu)
    plantuml $1 
    feh "$base.png" &
    ;;
  *.md)
    $(cat $CACHE/default_pdf.txt) "$base.pdf" &
    ;;
  *.sh)
    $1
    ;;
  *.jl)
    julia $1
    ;;
  *)
    if [ ! -z "$(grep '#!/bin/sh' $1)" ]; then
      $1
    else
      printf "\nNo execution method for this type of file!\n"
    fi
    ;;
esac
