#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# change cd to automatically ls
function cd {
  builtin cd "$@" && ls --color=auto 
}
# ls aliases
alias ls='ls --color=auto'
alias la='ls -la'
# vim aliases
alias v='vim'
alias vi='vim'
# git aliases
alias ga='git add'
alias gc='git commit -m'
alias gp='git push'
alias gst='git status'
alias gd='git diff'
# checkbashisms alias
alias cb='checkbashisms'

#Configures the shell prompt
PS1='\e[1;35m\u@\h \e[33m\w \e[36m\D{%T}\e[37m \n$ '

# Enable vi mode
set -o vi

# XTerm transparency
[ -n "$XTERM_VERSION" ] && transset-df -m 0.9 --id "$WINDOWID" >/dev/null
