#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias v='vim'
alias vi='vim'

#Configures the shell prompt
PS1='\[\033[00m\][\[\033[32m\]\u@\h\[\033[00m\]: \[\033[36m\]\w\[\033[00m\]]$ '

# Enable vi mode
set -o vi

# XTerm transparency
[ -n "$XTERM_VERSION" ] && transset-df -m 0.9 --id "$WINDOWID" >/dev/null
